FROM golang:1.25-alpine AS builder

RUN apk add --no-cache git
RUN go install go.k6.io/xk6/cmd/xk6@latest

WORKDIR /build
COPY go.mod tcp.go ./
RUN xk6 build --with xk6-tcp-throttling=. --output k6
COPY tests/test-script.js ./
CMD ["./k6", "run", "--out", "json=/results/results.json", "test-script.js"]

# FROM alpine:latest
# RUN apk --no-cache add ca-certificates
# WORKDIR /app
# COPY --from=builder /build/k6 .
# COPY test-script.js .
# RUN mkdir -p /results

# CMD ["./k6", "run", "--out", "json=/results/results.json", "test-script.js"]